# glsl_optimizer sources (from LTW's Android.mk)
set(GLSL_OPTIMIZER_SRC
  ${LTW_DIR}/glsl_optimizer/src/code/ir_print_glsl_visitor.cpp
  ${LTW_DIR}/glsl_optimizer/src/code/optimizer.cpp
  ${LTW_DIR}/glsl_optimizer/src/code/c_wrapper.cpp
  ${LTW_DIR}/glsl_optimizer/src/code/GlslConvert.cpp
  ${LTW_DIR}/glsl_optimizer/src/code/ir_print_ir_visitor.cpp
  ${LTW_DIR}/glsl_optimizer/src/util/compat_layer.cpp
  ${LTW_DIR}/glsl_optimizer/src/util/u_qsort.cpp
  ${LTW_DIR}/glsl_optimizer/src/util/u_debug_stack_android.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir_types.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/ir_validate.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/hir_field_selection.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/builtin_variables.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/glsl_parser.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/generate_ir.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/glsl_to_nir.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/ir_array_refcount.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/lower_instructions.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/lower_discard_flow.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/opt_dead_builtin_variables.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/link_varyings.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/glsl_parser_extras.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/builtin_types.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/opt_algebraic.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/lower_named_interface_blocks.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/link_uniforms.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/ir.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/opt_tree_grafting.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/ir_constant_expression.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/ast_type.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/lower_jumps.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/opt_if_simplification.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/ir_hierarchical_visitor.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/ir_builder.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/ast_array_index.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/propagate_invariance.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/ir_hv_accept.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/lower_builtins.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/link_interface_blocks.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/ast_to_hir.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/ir_function_detect_recursion.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/lower_packing_builtins.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/loop_analysis.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/ir_rvalue_visitor.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/ir_clone.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/opt_flip_matrices.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/opt_dead_code.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/link_uniform_block_active_visitor.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/s_expression.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/ir_reader.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/ir_equals.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/ir_function_can_inline.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/lower_vec_index_to_cond_assign.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/lower_variable_index_to_cond_assign.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/standalone_scaffolding.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/link_uniform_blocks.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/opt_function_inlining.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/lower_mat_op_to_vec.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/lower_blend_equation_advanced.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/ir_expression_flattening.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/opt_dead_code_local.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/opt_flatten_nested_if_blocks.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/ir_function.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/lower_precision.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/ir_variable_refcount.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/lower_vector_derefs.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/builtin_functions.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/linker_util.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/lower_distance.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/opt_rebalance_tree.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/linker.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/opt_dead_functions.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/glsl_symbol_table.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/lower_subroutine.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/glsl_lexer.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/link_functions.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/lower_int64.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/lower_discard.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/string_to_uint_map.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/ast_function.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/ast_expr.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/ir_print_visitor.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/opt_minmax.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/ir_basic_block.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/ir_builder_print_visitor.cpp
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl_types.cpp
  ${LTW_DIR}/glsl_optimizer/src/util/sha1/sha1.c
  ${LTW_DIR}/glsl_optimizer/src/util/u_debug_stack.c
  ${LTW_DIR}/glsl_optimizer/src/util/u_vector.c
  ${LTW_DIR}/glsl_optimizer/src/util/u_debug.c
  ${LTW_DIR}/glsl_optimizer/src/util/bitscan.c
  ${LTW_DIR}/glsl_optimizer/src/util/vma.c
  ${LTW_DIR}/glsl_optimizer/src/util/half_float.c
  ${LTW_DIR}/glsl_optimizer/src/util/u_idalloc.c
  ${LTW_DIR}/glsl_optimizer/src/util/u_process.c
  ${LTW_DIR}/glsl_optimizer/src/util/rgtc.c
  ${LTW_DIR}/glsl_optimizer/src/util/u_worklist.c
  ${LTW_DIR}/glsl_optimizer/src/util/sparse_array.c
  ${LTW_DIR}/glsl_optimizer/src/util/u_dl.c
  ${LTW_DIR}/glsl_optimizer/src/util/os_file.c
  ${LTW_DIR}/glsl_optimizer/src/util/fossilize_db.c
  ${LTW_DIR}/glsl_optimizer/src/util/u_thread.c
  ${LTW_DIR}/glsl_optimizer/src/util/build_id.c
  ${LTW_DIR}/glsl_optimizer/src/util/u_printf.c
  ${LTW_DIR}/glsl_optimizer/src/util/rb_tree.c
  ${LTW_DIR}/glsl_optimizer/src/util/register_allocate.c
  ${LTW_DIR}/glsl_optimizer/src/util/fast_idiv_by_const.c
  ${LTW_DIR}/glsl_optimizer/src/util/disk_cache_os.c
  ${LTW_DIR}/glsl_optimizer/src/util/blob.c
  ${LTW_DIR}/glsl_optimizer/src/util/strtod.c
  ${LTW_DIR}/glsl_optimizer/src/util/os_misc.c
  ${LTW_DIR}/glsl_optimizer/src/util/hash_table.c
  ${LTW_DIR}/glsl_optimizer/src/util/u_atomic.c
  ${LTW_DIR}/glsl_optimizer/src/util/softfloat.c
  ${LTW_DIR}/glsl_optimizer/src/util/crc32.c
  ${LTW_DIR}/glsl_optimizer/src/util/rand_xor.c
  ${LTW_DIR}/glsl_optimizer/src/util/os_memory_fd.c
  ${LTW_DIR}/glsl_optimizer/src/util/u_hash_table.c
  ${LTW_DIR}/glsl_optimizer/src/util/double.c
  ${LTW_DIR}/glsl_optimizer/src/util/slab.c
  ${LTW_DIR}/glsl_optimizer/src/util/futex.c
  ${LTW_DIR}/glsl_optimizer/src/util/u_queue.c
  ${LTW_DIR}/glsl_optimizer/src/util/u_call_once.c
  ${LTW_DIR}/glsl_optimizer/src/util/disk_cache.c
  ${LTW_DIR}/glsl_optimizer/src/util/set.c
  ${LTW_DIR}/glsl_optimizer/src/util/u_debug_memory.c
  ${LTW_DIR}/glsl_optimizer/src/util/u_math.c
  ${LTW_DIR}/glsl_optimizer/src/util/mesa_cache_db.c
  ${LTW_DIR}/glsl_optimizer/src/util/simple_mtx.c
  ${LTW_DIR}/glsl_optimizer/src/util/mesa-sha1.c
  ${LTW_DIR}/glsl_optimizer/src/util/log.c
  ${LTW_DIR}/glsl_optimizer/src/util/compress.c
  ${LTW_DIR}/glsl_optimizer/src/util/format/u_format_rgtc.c
  ${LTW_DIR}/glsl_optimizer/src/util/format/u_format_etc.c
  ${LTW_DIR}/glsl_optimizer/src/util/format/u_format_unpack_neon.c
  ${LTW_DIR}/glsl_optimizer/src/util/format/u_format_zs.c
  ${LTW_DIR}/glsl_optimizer/src/util/format/u_format_latc.c
  ${LTW_DIR}/glsl_optimizer/src/util/format/u_format_table.c
  ${LTW_DIR}/glsl_optimizer/src/util/format/u_format.c
  ${LTW_DIR}/glsl_optimizer/src/util/format/u_format_other.c
  ${LTW_DIR}/glsl_optimizer/src/util/format/u_format_fxt1.c
  ${LTW_DIR}/glsl_optimizer/src/util/format/u_format_bptc.c
  ${LTW_DIR}/glsl_optimizer/src/util/format/u_format_s3tc.c
  ${LTW_DIR}/glsl_optimizer/src/util/format/u_format_yuv.c
  ${LTW_DIR}/glsl_optimizer/src/util/string_buffer.c
  ${LTW_DIR}/glsl_optimizer/src/util/os_socket.c
  ${LTW_DIR}/glsl_optimizer/src/util/mesa_cache_db_multipart.c
  ${LTW_DIR}/glsl_optimizer/src/util/u_cpu_detect.c
  ${LTW_DIR}/glsl_optimizer/src/util/u_mm.c
  ${LTW_DIR}/glsl_optimizer/src/util/u_debug_describe.c
  ${LTW_DIR}/glsl_optimizer/src/util/anon_file.c
  ${LTW_DIR}/glsl_optimizer/src/util/dag.c
  ${LTW_DIR}/glsl_optimizer/src/util/format_srgb.c
  ${LTW_DIR}/glsl_optimizer/src/util/ralloc.c
  ${LTW_DIR}/glsl_optimizer/src/util/os_time.c
  ${LTW_DIR}/glsl_optimizer/src/util/u_debug_refcnt.c
  ${LTW_DIR}/glsl_optimizer/src/util/u_debug_symbol.c
  ${LTW_DIR}/glsl_optimizer/src/util/streaming-load-memcpy.c
  ${LTW_DIR}/glsl_optimizer/src/mesa/main/debug_output.c
  ${LTW_DIR}/glsl_optimizer/src/mesa/main/errors.c
  ${LTW_DIR}/glsl_optimizer/src/mesa/main/extensions_table.c
  ${LTW_DIR}/glsl_optimizer/src/mesa/main/imports.c
  ${LTW_DIR}/glsl_optimizer/src/mesa/program/symbol_table.c
  ${LTW_DIR}/glsl_optimizer/src/mesa/program/prog_parameter.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/gl_nir_link_uniform_initializers.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/gl_nir_lower_packed_varyings.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/gl_nir_opt_dead_builtin_varyings.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/gl_nir_lower_xfb_varying.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/gl_nir_lower_atomics.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/glcpp/glcpp.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/glcpp/glcpp-parse.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/glcpp/pp.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/glcpp/pp_standalone_scaffolding.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/glcpp/glcpp-lex.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/gl_nir_lower_samplers_as_deref.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/gl_nir_lower_buffers.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/gl_nir_link_uniforms.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/gl_nir_link_varyings.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/gl_nir_linker.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/gl_nir_link_xfb.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/gl_nir_link_atomics.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/gl_nir_link_uniform_blocks.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/gl_nir_lower_samplers.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/glsl/gl_nir_lower_images.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/shader_enums.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opcodes.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_from_ssa.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_point_smooth.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_shrink_vectors.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_wpos_ytransform.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_metadata.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_bit_size.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_shader_calls.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_printf.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_clip.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_scale_fdiv.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_preamble.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_dead_write_vars.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_inline_functions.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_sysvals_to_varyings.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_two_sided_color.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_remove_phis.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_phis_to_scalar.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_copy_propagate.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_vec_to_movs.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_phi_builder.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_single_sampled.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_peephole_select.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_cse.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_dead_cf.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_returns.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_discard_or_demote.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_normalize_cubemap_coords.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_search.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_bool_to_bitsize.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_worklist.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_passthrough_gs.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_move_vec_src_uses_to_dest.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_packing.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_group_loads.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_gcm.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_viewport_transform.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_gather_xfb_info.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_subgroups.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_gather_ssa_types.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_clip_halfz.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_builder.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_deref.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_shrink_stores.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_int64.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_load_store_vectorize.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_algebraic.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_mem_access_bit_sizes.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_find_array_copies.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_bool_to_int32.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_barriers.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_passthrough_edgeflags.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_constant_folding.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_move_discards_to_top.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_goto_ifs.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_image.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_repair_ssa.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_memory_model.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_cl_images.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_ray_queries.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_poly_line_smooth.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_vectorize.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_pntc_ytransform.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_variable_initializers.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_interpolation.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_comparison_pre.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_if.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_io_to_scalar.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_sink.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_builtin_builder.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_split_64bit_vec3_and_vec4.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_alpha_test.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_readonly_images_to_tex.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_offsets.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_liveness.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_io_to_temporaries.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_task_shader.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_intrinsics.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_frexp.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_validate.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_ubo_vec4.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_continue_constructs.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_vars_to_ssa.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_mod_analysis.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_access.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_alu_width.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_bool_to_float.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_global_vars_to_local.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_tex_shadow.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_split_var_copies.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_rematerialize_compares.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_system_values.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_inline_uniforms.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_dominance.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_texcoord_replace_late.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_gs_count_vertices.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_print.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_copy_prop_vars.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_indirect_derefs.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_phi_precision.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_fragdepth.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_is_helper_invocation.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_point_size.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_uniform_atomics.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_flrp.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_loop_unroll.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_clone.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_texcoord_replace.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_samplers.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_clip_disable.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_io_to_vector.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_split_vars.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_input_attachments.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_schedule.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_fragcolor.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_tex.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_range_analysis.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_regs_to_ssa.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_blend.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_divergence_analysis.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_drawpixels.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_trivial_continues.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_idiv_const.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_fragcoord_wtrans.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_bitmap.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_passthrough_tcs.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_undef.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_gather_info.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_wrmasks.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_vec3_to_vec4.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_serialize.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_idiv.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_non_uniform_access.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_array_deref_of_vec.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_control_flow.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_large_constants.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_wpos_center.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_constant_expressions.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_linking_helpers.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_instr_set.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_mediump.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_split_per_member_structs.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_convert_alu_types.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_gs_intrinsics.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_int_to_float.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_to_source_mods.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_remove_dead_variables.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_alu.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_var_copies.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_discard_if.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_atomics_to_ssbo.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_fb_read.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_flatshade.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_clip_cull_distance_arrays.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_propagate_invariant.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_helper_writes.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_const_arrays_to_uniforms.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_memcpy.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_conditional_discard.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_to_lcssa.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_sweep.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_uniforms_to_ubo.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_combine_stores.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_fp16_conv.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_clamp_color_outputs.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_point_size_mov.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_dce.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_double_ops.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_non_uniform_access.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_ssbo.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_load_const_to_scalar.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_io.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_scratch.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_opt_move.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_amul.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_multiview.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_patch_vertices.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_undef_to_zero.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_io_arrays_to_elements.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_loop_analyze.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_memcpy.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_intrinsics.c
  ${LTW_DIR}/glsl_optimizer/src/compiler/nir/nir_lower_locals_to_regs.c
)

set(LTW_CORE_SRC
  ${LTW_DIR}/egl.c
  ${LTW_DIR}/proc.c
  ${LTW_DIR}/main.c
  ${LTW_DIR}/glformats.c
  ${LTW_DIR}/basevertex.c
  ${LTW_DIR}/blending.c
  ${LTW_DIR}/query.c
  ${LTW_DIR}/shader_wrapper.c
  ${LTW_DIR}/string_utils.c
  ${LTW_DIR}/framebuffer.c
  ${LTW_DIR}/of_buffer_copier.c
  ${LTW_DIR}/stubs.c
  ${LTW_DIR}/multidraw.c
  ${LTW_DIR}/vertexattrib.c
  ${LTW_DIR}/swizzle.c
  ${LTW_DIR}/license_notice.c
  ${LTW_DIR}/env.c
  ${LTW_DIR}/vgpu_shaderconv/shaderconv.c
  ${LTW_DIR}/unordered_map/unordered_map.c
  ${LTW_DIR}/unordered_map/int_hash.c
)
